on:
  push:
    branches: [master, main]
    tags-ignore:
      - "v*"
    paths-ignore:
      - "**.css"
      - "**.tpl"
      - "**.txt"
      - "**.md"
  pull_request:
    branches: [master, main]
    paths-ignore:
      - "**.css"
      - "**.tpl"
      - "**.md"
      - "**.txt"
      - "**.yml"

jobs:
  frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # 7.0.0
        with:
          node-version: "lts/*"

      - name: Install JavaScript Dependencies
        run: npm install

      - name: Run Tests
        run: npm run-script check-syntax

  php_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ["7.2", "7.3", "7.4", "8.1", "8.2", "8.3", "8.4", "8.5"]
    name: PHP ${{ matrix.php-versions }} Test
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # 7.0.0
        with:
          node-version: "lts/*"

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          extensions: soap
          tools: composer, phpcs, phpunit:8.5.29

      - name: Check Style/Syntax
        run: phpcs

      - name: Run Tests
        run: phpunit
