name: Release

permissions:
  contents: write
  packages: write

on:
  release:
    types: [ released ]

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
        
      - name: Build
        run: make build
        
      - name: Attach Build to Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          files: ./synergy-wholesale-domains-${{ github.ref_name }}.zip
